// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ControlsModuleScssNamespace {
  export interface IControlsModuleScss {
    btn: string;
    theadRow: string;
  }
}

declare const ControlsModuleScssModule: ControlsModuleScssNamespace.IControlsModuleScss;

export = ControlsModuleScssModule;
