// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace LayoutModuleScssNamespace {
  export interface ILayoutModuleScss {
    content: string;
  }
}

declare const LayoutModuleScssModule: LayoutModuleScssNamespace.ILayoutModuleScss;

export = LayoutModuleScssModule;
