// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace RootScssNamespace {
  export interface IRootScss {
    app: string;
  }
}

declare const RootScssModule: RootScssNamespace.IRootScss;

export = RootScssModule;
