// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ExampleModuleScssNamespace {
  export interface IExampleModuleScss {
    AppExample: string;
  }
}

declare const ExampleModuleScssModule: ExampleModuleScssNamespace.IExampleModuleScss;

export = ExampleModuleScssModule;
