// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HomeAppModuleScssNamespace {
  export interface IHomeAppModuleScss {
    AppFooter: string;
    AppHeader: string;
    FooterLink: string;
  }
}

declare const HomeAppModuleScssModule: HomeAppModuleScssNamespace.IHomeAppModuleScss;

export = HomeAppModuleScssModule;
