// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace CounterModuleScssNamespace {
  export interface ICounterModuleScss {
    btn: string;
    label: string;
  }
}

declare const CounterModuleScssModule: CounterModuleScssNamespace.ICounterModuleScss;

export = CounterModuleScssModule;
