// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NavbarModuleScssNamespace {
  export interface INavbarModuleScss {
    active: string;
    link: string;
    navbar: string;
  }
}

declare const NavbarModuleScssModule: NavbarModuleScssNamespace.INavbarModuleScss;

export = NavbarModuleScssModule;
